### ISSUE TITLE
TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by ruslan-ardashev** [miketalley/xbox-series-x-finder#3]
Getting the following error:

TypeError: Cannot read property 'childNodes' of undefined
    at checkTarget (/Users/ruslan/Developer/xbox-series-x-finder/finder.js:73:5)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Timeout._onTimeout (/Users/ruslan/Developer/xbox-series-x-finder/finder.js:147:5)
npm ERR! code 1
npm ERR! path /Users/ruslan/Developer/xbox-series-x-finder
npm ERR! command failed
npm ERR! command sh -c node finder.js

**Comment by miketalley** [comment]
Hey @ruslan120101 this is due to popfindr.com changing the way their site works. For now, it looks like they have prevented scraping data from their site. They obtain data from private Target.com APIs which I do not have access to. This has rendered the xbox-series-x-finder useless for the time being until I can find a way to get the API access.
